spring.application.name=bita2ti
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/bita2ti
spring.datasource.username=root
spring.datasource.password=W0W_b@z3lgum&&67

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.igflex@gmail.com
spring.mail.password=srekzathqzltkxqc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true